import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const runtimeRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const familyRoot = dirname(runtimeRoot);

const component = (environment, directory) =>
  resolve(process.env[environment] ?? join(familyRoot, directory));

export const componentRoots = Object.freeze({
  duallity: component("VINARY_TREE_DUALLITY_ROOT", "duallity"),
  interop: component("VINARY_TREE_INTEROP_ROOT", "vinary-tree-interop"),
  llattice: component("VINARY_TREE_LLATTICE_ROOT", "llattice"),
  libdictenstein: component("VINARY_TREE_LIBDICTENSTEIN_ROOT", "libdictenstein"),
  liblevenshtein: component("VINARY_TREE_LIBLEVENSHTEIN_ROOT", "liblevenshtein-rust"),
  llingLlang: component("VINARY_TREE_LLING_LLANG_ROOT", "lling-llang"),
});

const isWithin = (parent, candidate) => {
  const path = relative(parent, candidate);
  return path === "" || (!path.startsWith("..") && !isAbsolute(path));
};

export function requireComponentRoots() {
  for (const [name, root] of Object.entries(componentRoots)) {
    if (isWithin(runtimeRoot, root)) {
      throw new Error(
        `${name} must be checked out beside ${runtimeRoot}, not beneath it; ` +
        "nested owner builds inherit the runtime Cargo patch overlay",
      );
    }
    if (!existsSync(join(root, "Cargo.toml"))) {
      throw new Error(`${name} Cargo.toml is missing under ${root}`);
    }
  }
}

export function cargoPackageVersion(root) {
  const manifest = readFileSync(join(root, "Cargo.toml"), "utf8");
  const packageSection = manifest.match(/\[package\]([\s\S]*?)(?:\n\[|$)/)?.[1];
  const version = packageSection?.match(/^version\s*=\s*"([^"]+)"/m)?.[1];
  if (version === undefined) throw new Error(`package version is missing from ${root}/Cargo.toml`);
  return version;
}

const tomlPath = (path) => JSON.stringify(path);

export function writeLocalCargoConfig() {
  requireComponentRoots();
  const directory = join(runtimeRoot, ".cargo");
  const path = join(directory, "config.toml");
  mkdirSync(directory, { recursive: true });
  const config = `# Generated by npm run configure:local; never publish this path overlay.
[patch.crates-io]
duallity = { path = ${tomlPath(componentRoots.duallity)} }
llattice = { path = ${tomlPath(componentRoots.llattice)} }
libdictenstein = { path = ${tomlPath(componentRoots.libdictenstein)} }
liblevenshtein = { path = ${tomlPath(componentRoots.liblevenshtein)} }
lling-llang = { path = ${tomlPath(componentRoots.llingLlang)} }
vinary-tree-interop = { path = ${tomlPath(componentRoots.interop)} }

[target.'cfg(all(any(target_arch = "x86", target_arch = "x86_64"), any(target_os = "linux", target_os = "macos", target_os = "windows")))']
rustflags = ["-C", "target-feature=+aes,+sse2"]

[target.'cfg(all(any(target_arch = "arm", target_arch = "aarch64"), any(target_os = "linux", target_os = "macos", target_os = "windows")))']
rustflags = ["-C", "target-feature=+aes,+neon"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\\"wasm_js\\""]
`;
  writeFileSync(path, config);
  return path;
}
